---
- name: Extend password expiration for ncloud account
  hosts: all
  become: yes  # root 권한으로 실행
  tasks:
    - name: Set password expiration to never for ncloud user
      ansible.builtin.command:
        cmd: chage -d "{{ date }}" ncloud
      register: result
      changed_when: result.rc == 0
      failed_when: result.rc != 0
