---
- name: Extend password expiration for ncloud account
  become: yes
  tasks:
    - name: Set password expiration to never for ncloud user
      ansible.builtin.command:
        cmd: chage -d 0 ncloud
      register: result
      changed_when: result.rc == 0
      failed_when: result.rc != 0
