---
- name: Extend password expiration for ncloud account
  hosts: all
  become: yes
  tasks:
    - name: Set password expiration for ncloud user
      ansible.posix.passwd:
        name: "{{ ncloud_user }}"
        password_change_date: "{{ password_change_date }}"
      register: result
      changed_when: result.changed
      failed_when: result.failed
