---
- name: Extend password expiration for ncloud account to today
  hosts: all
  become: yes  # root 권한으로 실행
  tasks:
    - name: Get current date
      ansible.builtin.set_fact:
        current_date: "{{ ansible_date_time.date }}"

    - name: Set password expiration to today for ncloud user
      ansible.builtin.command:
        cmd: chage -d {{ current_date }} ncloud
      register: result
      changed_when: result.rc == 0
      failed_when: result.rc != 0
