---
- name: Extend password expiration for ncloud account
  hosts: all
  become: yes
  tasks:
    - name: Get current date
      ansible.builtin.set_fact:
        current_date: "{{ ansible_date_time.date }}"
        
    - name: Set password expiration to never for ncloud user
      ansible.builtin.command:
        cmd: chage -d {{ current_date }} ncloud
      register: result
      changed_when: result.rc == 0
      failed_when: result.rc != 0
