---
- name: Extend password expiration for ncloud account
  hosts: all
  become: yes
  tasks:
    - name: Set password expiration to never for ncloud user
      user:
       name: "{{ user }}"
       date: "{{ date }}"
       ansible.builtin.command:
        cmd: chage -d "{{ date }}" "{{ user }}"
       register: result
       changed_when: result.rc == 0
       failed_when: result.rc != 0
