---
- name: Extend password expiration for ncloud account
  hosts: all
  become: yes  # root 권한으로 실행
  gather_facts: no
  tasks:
    - name: Get current date if not provided
      ansible.builtin.set_fact:
        date: "{{ ansible_date_time.date }}"
      when: date is not defined or date == ""

    - name: Set password expiration for ncloud user
      ansible.builtin.command:
        cmd: chage -d "{{ date }}" "{{ ncloud_user | default('ncloud') }}"
      register: result
      changed_when: result.rc == 0
      failed_when: result.rc != 0
