---
- name: Extend password expiration for ncloud account
  hosts: all
  become: yes  # root 권한으로 실행
  tasks:
    - name: Get current date if not provided
      ansible.builtin.set_fact:
        date: "{{ ansible_date_time.date }}"
      when: date is not defined or date == ""

    - name: Set password expiration for ncloud user
      ansible.posix.passwd:
        name: "{{ ncloud_user | default('ncloud') }}"
        password_change_date: "{{ date }}"
      register: result
      changed_when: result.changed
      failed_when: result.failed
